name: tic_tac_toe
description: Tic tac toe game

version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  tuple: 1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2

dev_dependencies:
  flutter_launcher_icons: 0.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
